// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/log_entry.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class GPBAny;
@class GPBStruct;
@class GPBTimestamp;
@class HttpRequest;
@class LogEntryOperation;
@class MonitoredResource;
GPB_ENUM_FWD_DECLARE(LogSeverity);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LogEntryRoot

@interface LogEntryRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - LogEntry

typedef GPB_ENUM(LogEntry_FieldNumber) {
  LogEntry_FieldNumber_ProtoPayload = 2,
  LogEntry_FieldNumber_TextPayload = 3,
  LogEntry_FieldNumber_InsertId = 4,
  LogEntry_FieldNumber_JsonPayload = 6,
  LogEntry_FieldNumber_HTTPRequest = 7,
  LogEntry_FieldNumber_Resource = 8,
  LogEntry_FieldNumber_Timestamp = 9,
  LogEntry_FieldNumber_Severity = 10,
  LogEntry_FieldNumber_Labels = 11,
  LogEntry_FieldNumber_LogName = 12,
  LogEntry_FieldNumber_Operation = 15,
};

typedef GPB_ENUM(LogEntry_Payload_OneOfCase) {
  LogEntry_Payload_OneOfCase_GPBUnsetOneOfCase = 0,
  LogEntry_Payload_OneOfCase_ProtoPayload = 2,
  LogEntry_Payload_OneOfCase_TextPayload = 3,
  LogEntry_Payload_OneOfCase_JsonPayload = 6,
};

// An individual entry in a log.
@interface LogEntry : GPBMessage

// Required. The resource name of the log to which this log entry
// belongs. The format of the name is
// `projects/&lt;project-id&gt;/logs/&lt;log-id%gt;`.  Examples:
// `"projects/my-projectid/logs/syslog"`,
// `"projects/1234567890/logs/library.googleapis.com%2Fbook_log"`.
//
// The log ID part of resource name must be less than 512 characters
// long and can only include the following characters: upper and
// lower case alphanumeric characters: [A-Za-z0-9]; and punctuation
// characters: forward-slash, underscore, hyphen, and period.
// Forward-slash (`/`) characters in the log ID must be URL-encoded.
@property(nonatomic, readwrite, copy, null_resettable) NSString *logName;

// Required. The monitored resource associated with this log entry.
// Example: a log entry that reports a database error would be
// associated with the monitored resource designating the particular
// database that reported the error.
@property(nonatomic, readwrite) BOOL hasResource;
@property(nonatomic, readwrite, strong, null_resettable) MonitoredResource *resource;

// Required. The log entry payload, which can be one of multiple types.
@property(nonatomic, readonly) LogEntry_Payload_OneOfCase payloadOneOfCase;

// The log entry payload, represented as a protocol buffer.
// You can only use `protoPayload` values that belong to a set of approved
// types.
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *protoPayload;

// The log entry payload, represented as a Unicode string (UTF-8).
@property(nonatomic, readwrite, copy, null_resettable) NSString *textPayload;

// The log entry payload, represented as a structure that
// is expressed as a JSON object.
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *jsonPayload;

// Optional. The time the event described by the log entry occurred.  If
// omitted, Cloud Logging will use the time the log entry is written.
@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *timestamp;

// Optional. The severity of the log entry. The default value is
// `LogSeverity.DEFAULT`.
@property(nonatomic, readwrite) enum LogSeverity severity;

// Optional. A unique ID for the log entry. If you provide this field, the
// logging service considers other log entries in the same log with the same
// ID as duplicates which can be removed.
// If omitted, Cloud Logging will generate a unique ID for this log entry.
@property(nonatomic, readwrite, copy, null_resettable) NSString *insertId;

// Optional. Information about the HTTP request associated with this log entry,
// if applicable.
@property(nonatomic, readwrite) BOOL hasHTTPRequest;
@property(nonatomic, readwrite, strong, null_resettable) HttpRequest *hTTPRequest;

// Optional. A set of user-defined (key, value) data that provides additional
// information about the log entry.
// |labels| values are |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary *labels;
@property(nonatomic, readonly) NSUInteger labels_Count;

// Optional. Information about an operation associated with the log entry, if
// applicable.
@property(nonatomic, readwrite) BOOL hasOperation;
@property(nonatomic, readwrite, strong, null_resettable) LogEntryOperation *operation;

@end

int32_t LogEntry_Severity_RawValue(LogEntry *message);
void SetLogEntry_Severity_RawValue(LogEntry *message, int32_t value);

void LogEntry_ClearPayloadOneOfCase(LogEntry *message);

#pragma mark - LogEntryOperation

typedef GPB_ENUM(LogEntryOperation_FieldNumber) {
  LogEntryOperation_FieldNumber_Id_p = 1,
  LogEntryOperation_FieldNumber_Producer = 2,
  LogEntryOperation_FieldNumber_First = 3,
  LogEntryOperation_FieldNumber_Last = 4,
};

// Additional information about a potentially long-running operation with which
// a log entry is associated.
@interface LogEntryOperation : GPBMessage

// Required. An arbitrary operation identifier. Log entries with the
// same identifier are assumed to be part of the same operation.
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

// Required. An arbitrary producer identifier. The combination of
// `id` and `producer` must be globally unique.  Examples for `producer`:
// `"MyDivision.MyBigCompany.com"`, "github.com/MyProject/MyApplication"`.
@property(nonatomic, readwrite, copy, null_resettable) NSString *producer;

// Optional. Set this to True if this is the first log entry in the operation.
@property(nonatomic, readwrite) BOOL first;

// Optional. Set this to True if this is the last log entry in the operation.
@property(nonatomic, readwrite) BOOL last;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
