// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/date.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DateRoot

@interface DateRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Date

typedef GPB_ENUM(Date_FieldNumber) {
  Date_FieldNumber_Year = 1,
  Date_FieldNumber_Month = 2,
  Date_FieldNumber_Day = 3,
};

// Represents a whole calendar date, e.g. date of birth. The time of day and
// time zone are either specified elsewhere or are not significant. The date
// is relative to the Proleptic Gregorian Calendar. The day may be 0 to
// represent a year and month where the day is not significant, e.g. credit card
// expiration date. The year may be 0 to represent a month and day independent
// of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]
// and [google.protobuf.Timestamp][google.protobuf.Timestamp].
@interface Date : GPBMessage

// Year of date. Must be from 1 to 9,999, or 0 if specifying a date without
// a year.
@property(nonatomic, readwrite) int32_t year;

// Month of year of date. Must be from 1 to 12.
@property(nonatomic, readwrite) int32_t month;

// Day of month. Must be from 1 to 31 and valid for the year and month, or 0
// if specifying a year/month where the day is not sigificant.
@property(nonatomic, readwrite) int32_t day;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
