// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/dayofweek.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum DayOfWeek

// Represents a day of week.
typedef GPB_ENUM(DayOfWeek) {
  DayOfWeek_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  // The unspecified day-of-week.
  DayOfWeek_DayOfWeekUnspecified = 0,

  // The day-of-week of Monday.
  DayOfWeek_Monday = 1,

  // The day-of-week of Tuesday.
  DayOfWeek_Tuesday = 2,

  // The day-of-week of Wednesday.
  DayOfWeek_Wednesday = 3,

  // The day-of-week of Thursday.
  DayOfWeek_Thursday = 4,

  // The day-of-week of Friday.
  DayOfWeek_Friday = 5,

  // The day-of-week of Saturday.
  DayOfWeek_Saturday = 6,

  // The day-of-week of Sunday.
  DayOfWeek_Sunday = 7,
};

GPBEnumDescriptor *DayOfWeek_EnumDescriptor(void);

BOOL DayOfWeek_IsValidValue(int32_t value);

#pragma mark - DayofweekRoot

@interface DayofweekRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
