// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/type/dayofweek.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "google/type/Dayofweek.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - DayofweekRoot

@implementation DayofweekRoot

@end

#pragma mark - Enum DayOfWeek

GPBEnumDescriptor *DayOfWeek_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageEnumValueDescription values[] = {
      { .name = "DayOfWeekUnspecified", .number = DayOfWeek_DayOfWeekUnspecified },
      { .name = "Monday", .number = DayOfWeek_Monday },
      { .name = "Tuesday", .number = DayOfWeek_Tuesday },
      { .name = "Wednesday", .number = DayOfWeek_Wednesday },
      { .name = "Thursday", .number = DayOfWeek_Thursday },
      { .name = "Friday", .number = DayOfWeek_Friday },
      { .name = "Saturday", .number = DayOfWeek_Saturday },
      { .name = "Sunday", .number = DayOfWeek_Sunday },
    };
    descriptor = [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(DayOfWeek)
                                                   values:values
                                               valueCount:sizeof(values) / sizeof(GPBMessageEnumValueDescription)
                                             enumVerifier:DayOfWeek_IsValidValue];
  }
  return descriptor;
}

BOOL DayOfWeek_IsValidValue(int32_t value__) {
  switch (value__) {
    case DayOfWeek_DayOfWeekUnspecified:
    case DayOfWeek_Monday:
    case DayOfWeek_Tuesday:
    case DayOfWeek_Wednesday:
    case DayOfWeek_Thursday:
    case DayOfWeek_Friday:
    case DayOfWeek_Saturday:
    case DayOfWeek_Sunday:
      return YES;
    default:
      return NO;
  }
}


// @@protoc_insertion_point(global_scope)
